version: '2'

services:

  bluetooth:
    build: .
    network_mode: host
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: 1
  
  # Only for testing, remove before merging
  audio:
      image: balenablocks/audio:raspberrypi4-64
      privileged: true
      labels:
        io.balena.features.dbus: 1
      ports:
        - 4317:4317